name: 'Kernel Signer'
author: 'EyeCantCU'
description: 'Signs kernel in image via Podman'
inputs:
  image:
    description: 'Image containing kernel'
    required: true
  imagename:
    description: 'Image containing kernel (just the name)'
    required: true
  privkey:
    description: 'Private key, path to private key, or URL to retrieve private key'
    default: '/etc/pki/kernel/private/private_key.priv'
    required: true
  pubkey:
    description: 'Public key, path to public key, or URL to retrieve public key'
    default: '/etc/pki/kernel/public/public_key.der'
    required: true
  tags:
    description: 'Tags used by container'
    default: 'latest'
    required: true
runs:
  using: "composite"
  steps:
    - name: Sign kernel
      shell: bash
      run: |
        CONTAINER_ID=$(docker run --entrypoint /bin/bash --name "${{ inputs.imagename }}" -dt "${{ inputs.image }}")
        docker cp "${{ github.action_path }}"/sign-kernel.sh "${{ inputs.imagename }}":/tmp/sign-kernel.sh
        docker cp "${{ github.action_path }}"/kernel_options.txt "${{ inputs.imagename }}":/tmp/kernel_options.txt
        docker exec -e PRIVKEY="${{ inputs.privkey }}" -e PUBKEY="${{ inputs.pubkey }}" "${{ inputs.imagename }}" "/tmp/sign-kernel.sh"
        docker commit "$CONTAINER_ID" "${{ inputs.imagename }}"
        for TAG in $TAGS; do
          echo "Tagging ${{ inputs.imagename }} with tag: $TAG"
          docker tag "${{ inputs.imagename }}" "${{ inputs.image }}":$TAG
        done
      env:
        TAGS: ${{ inputs.tags }}
